# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SSM/server/grpcproto/MainServer.proto
# Protobuf Python Version: 4.25.1
#https://github.com/ONETAPL3G3ND
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%SSM/server/grpcproto/MainServer.proto\"!\n\x0fMessageResponse\x12\x0e\n\x06Status\x18\x01 \x01(\x05\"#\n\x07Message\x12\x0c\n\x04Text\x18\x01 \x01(\t\x12\n\n\x02ID\x18\x02 \x01(\x05\x32\x37\n\nMainServer\x12)\n\x0bSendMessage\x12\x08.Message\x1a\x10.MessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SSM.server.grpcproto.MainServer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGERESPONSE']._serialized_start=41
  _globals['_MESSAGERESPONSE']._serialized_end=74
  _globals['_MESSAGE']._serialized_start=76
  _globals['_MESSAGE']._serialized_end=111
  _globals['_MAINSERVER']._serialized_start=113
  _globals['_MAINSERVER']._serialized_end=168
# @@protoc_insertion_point(module_scope)
